#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/mof/parser.y".
#

require 'racc/parser'



# parser.rb - generated by racc

require 'strscan'
require 'rubygems'
require 'cim'
require File.join(File.dirname(__FILE__), 'result')
require File.join(File.dirname(__FILE__), 'scanner')
require File.join(File.dirname(__FILE__), 'helper')


module MOF

  class Parser < Racc::Parser

module_eval <<'..end lib/mof/parser.y modeval..idbe2b713bdc', 'lib/mof/parser.y', 566

#
# Initialize MOF::Parser
#  MOF::Parser.new options = {}
#
#  options -> Hash of options
#    :debug -> boolean
#    :includes -> array of include dirs
#    :style -> :cim or :wmi
#
def initialize options = {}
  @yydebug = options[:debug]
  @includes = options[:includes] || []
  @quiet = options[:quiet]
  @style = options[:style] || :cim  # default to style CIM v2.2 syntax
  
  @lineno = 1
  @file = nil
  @iconv = nil
  @eol = "\n"
  @fname = nil
  @fstack = []
  @in_comment = false
  @seen_files = []
  @qualifiers = {}
end

#
# Make options hash from argv
#
# returns [ files, options ]
#

  def self.argv_handler name, argv
    files = []
    options = { :namespace => "" }
    while argv.size > 0
      case opt = argv.shift
      when "-h"
	$stderr.puts "Ruby MOF compiler"
	$stderr.puts "#{name} [-h] [-d] [-I <dir>] [<moffiles>]"
	$stderr.puts "Compiles <moffile>"
	$stderr.puts "\t-d  debug"
	$stderr.puts "\t-h  this help"
	$stderr.puts "\t-I <dir>  include dir"
	$stderr.puts "\t-f  force"
	$stderr.puts "\t-n <namespace>"
	$stderr.puts "\t-o <output>"
	$stderr.puts "\t-s <style>  syntax style (wmi,cim)"
	$stderr.puts "\t-q  quiet"
	$stderr.puts "\t<moffiles>  file(s) to read (else use $stdin)"
	exit 0
      when "-f" then options[:force] = true
      when "-s" then options[:style] = argv.shift.to_sym
      when "-d" then options[:debug] = true
      when "-q" then options[:quiet] = true
      when "-I"
	options[:includes] ||= []
	dirname = argv.shift
	unless File.directory?(dirname)
	  files << dirname
	  dirname = File.dirname(dirname)
	end
	options[:includes] << Pathname.new(dirname)
      when "-n" then options[:namespace] = argv.shift
      when "-o" then options[:output] = argv.shift
      when /^-.+/
	$stderr.puts "Undefined option #{opt}"
      else
	files << opt
      end
    end
    [ files, options ]
  end

include Helper
include Scanner

..end lib/mof/parser.y modeval..idbe2b713bdc

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 71, :_reduce_1,
 1, 71, :_reduce_2,
 2, 71, :_reduce_3,
 1, 72, :_reduce_none,
 1, 72, :_reduce_5,
 1, 72, :_reduce_6,
 1, 72, :_reduce_7,
 4, 73, :_reduce_8,
 4, 73, :_reduce_none,
 3, 73, :_reduce_10,
 1, 78, :_reduce_none,
 0, 77, :_reduce_12,
 3, 77, :_reduce_13,
 1, 79, :_reduce_none,
 3, 79, :_reduce_none,
 1, 80, :_reduce_none,
 1, 80, :_reduce_17,
 1, 80, :_reduce_none,
 9, 74, :_reduce_19,
 0, 87, :_reduce_20,
 2, 87, :_reduce_21,
 1, 88, :_reduce_none,
 1, 88, :_reduce_none,
 1, 88, :_reduce_none,
 0, 83, :_reduce_none,
 1, 83, :_reduce_26,
 4, 92, :_reduce_27,
 0, 94, :_reduce_28,
 3, 94, :_reduce_29,
 3, 93, :_reduce_30,
 0, 97, :_reduce_none,
 2, 97, :_reduce_32,
 0, 96, :_reduce_none,
 1, 96, :_reduce_none,
 3, 99, :_reduce_35,
 1, 99, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_none,
 1, 98, :_reduce_43,
 0, 85, :_reduce_none,
 1, 85, :_reduce_none,
 0, 86, :_reduce_none,
 1, 86, :_reduce_none,
 1, 84, :_reduce_48,
 2, 102, :_reduce_49,
 2, 104, :_reduce_50,
 2, 103, :_reduce_51,
 6, 89, :_reduce_52,
 6, 91, :_reduce_53,
 7, 90, :_reduce_54,
 1, 106, :_reduce_none,
 1, 106, :_reduce_56,
 1, 110, :_reduce_none,
 1, 110, :_reduce_58,
 1, 111, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_none,
 1, 105, :_reduce_74,
 1, 109, :_reduce_75,
 2, 109, :_reduce_76,
 0, 112, :_reduce_none,
 1, 112, :_reduce_none,
 2, 113, :_reduce_79,
 0, 115, :_reduce_80,
 3, 115, :_reduce_81,
 5, 114, :_reduce_82,
 1, 116, :_reduce_none,
 1, 116, :_reduce_none,
 1, 117, :_reduce_none,
 0, 107, :_reduce_none,
 1, 107, :_reduce_none,
 0, 118, :_reduce_none,
 1, 118, :_reduce_89,
 3, 119, :_reduce_90,
 0, 121, :_reduce_91,
 1, 121, :_reduce_none,
 0, 108, :_reduce_none,
 1, 108, :_reduce_none,
 2, 120, :_reduce_95,
 1, 122, :_reduce_none,
 1, 122, :_reduce_none,
 1, 122, :_reduce_none,
 3, 101, :_reduce_99,
 0, 124, :_reduce_none,
 1, 124, :_reduce_101,
 3, 124, :_reduce_102,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 1, 100, :_reduce_109,
 1, 82, :_reduce_none,
 1, 82, :_reduce_none,
 1, 82, :_reduce_none,
 1, 82, :_reduce_none,
 1, 82, :_reduce_none,
 1, 81, :_reduce_none,
 2, 81, :_reduce_116,
 1, 123, :_reduce_none,
 1, 123, :_reduce_none,
 2, 126, :_reduce_none,
 0, 127, :_reduce_none,
 2, 127, :_reduce_none,
 1, 129, :_reduce_none,
 3, 128, :_reduce_none,
 2, 130, :_reduce_none,
 0, 132, :_reduce_none,
 3, 132, :_reduce_none,
 3, 131, :_reduce_none,
 1, 133, :_reduce_none,
 1, 133, :_reduce_none,
 6, 75, :_reduce_130,
 0, 136, :_reduce_none,
 1, 136, :_reduce_none,
 1, 95, :_reduce_none,
 1, 95, :_reduce_none,
 1, 95, :_reduce_none,
 1, 95, :_reduce_none,
 4, 134, :_reduce_137,
 5, 135, :_reduce_138,
 1, 138, :_reduce_139,
 3, 138, :_reduce_140,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 1, 139, :_reduce_none,
 5, 137, :_reduce_151,
 1, 140, :_reduce_152,
 3, 140, :_reduce_153,
 2, 76, :_reduce_none,
 8, 125, :_reduce_none,
 1, 141, :_reduce_none,
 2, 141, :_reduce_none,
 5, 142, :_reduce_none,
 3, 142, :_reduce_159 ]

racc_reduce_n = 160

racc_shift_n = 235

racc_action_table = [
    16,   168,   147,   168,   164,   134,   164,    19,   160,   161,
   152,    28,    29,   168,     8,   165,   164,   165,   159,     8,
   162,   151,   153,   154,   155,    18,   147,   165,   123,   158,
   114,   115,   116,   117,   118,   119,   120,   200,   124,   197,
   164,    49,    51,    84,    87,    88,    89,    55,    56,    46,
    47,   147,     1,   165,   169,    42,    10,     1,    10,    10,
    41,    98,    35,    42,    10,    49,    51,    84,    87,    88,
    89,    55,    56,    46,    47,    54,   185,   126,   -77,    42,
   127,   184,    10,    10,    79,    98,    54,   182,   183,    80,
    49,    51,    84,    87,    88,    89,    55,    56,    46,    47,
    22,   131,    24,    20,    42,   132,    22,    10,    24,    20,
    98,    35,   133,    23,    49,    51,   112,    18,   113,    23,
    55,    56,    46,    47,    96,    49,    51,    35,   176,    10,
    10,    55,    56,    46,    47,    75,    62,    64,    66,    67,
    68,    69,    71,    72,    73,    74,    76,    61,    63,    65,
   -25,    75,    62,    64,    66,    67,    68,    69,    71,    72,
    73,    74,    76,    61,    63,    65,    13,    14,    94,    95,
    49,    51,    84,    87,    88,    89,    55,    56,    46,    47,
   160,   161,   152,   191,   192,   111,    22,    10,    24,    20,
   159,   149,   162,   151,   153,   154,   155,   150,   109,    23,
   107,   158,    49,    51,    84,    87,    88,    89,    55,    56,
    46,    47,   114,   115,   116,   117,   118,   119,   120,    10,
    49,    51,    84,    87,    88,    89,    55,    56,    46,    47,
   114,   115,   116,   117,   118,   119,   120,    10,    75,    62,
    64,    66,    67,    68,    69,    71,    72,    73,    74,    76,
    61,    63,    65,   104,   100,    35,   179,    98,    59,    96,
    92,   189,   190,    78,    59,    35,    31,   198,    31,    36,
    35,   205,   206,   104,   -59,   104,   209,    33,   127,   127,
    32,   218,   219,    31,   224,   225,    15,   227,   228,   230,
    10,   104,   127 ]

racc_action_check = [
     4,   136,   209,   190,   136,   109,   190,     5,   134,   134,
   134,    13,    13,   218,     0,   136,   218,   190,   134,     4,
   134,   134,   134,   134,   134,     5,   184,   218,    97,   134,
   150,   150,   150,   150,   150,   150,   150,   188,    98,   186,
   188,   209,   209,   209,   209,   209,   209,   209,   209,   209,
   209,   127,     0,   186,   137,   209,   137,     4,   209,     0,
    26,   209,   100,    26,     4,   184,   184,   184,   184,   184,
   184,   184,   184,   184,   184,    95,   166,   102,   206,   184,
   103,   166,   184,   206,    38,   184,    31,   156,   156,    38,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
    10,   104,    10,    10,   127,   106,    79,   127,    79,    79,
   127,   175,   107,    10,    95,    95,    91,    86,    91,    79,
    95,    95,    95,    95,    83,    31,    31,   214,   139,   123,
   139,    31,    31,    31,    31,   175,   175,   175,   175,   175,
   175,   175,   175,   175,   175,   175,   175,   175,   175,   175,
    42,   214,   214,   214,   214,   214,   214,   214,   214,   214,
   214,   214,   214,   214,   214,   214,     1,     1,    48,    48,
    42,    42,    42,    42,    42,    42,    42,    42,    42,    42,
   183,   183,   183,   180,   180,    81,     8,    42,     8,     8,
   183,   130,   183,   183,   183,   183,   183,   133,    78,     8,
    77,   183,    41,    41,    41,    41,    41,    41,    41,    41,
    41,    41,   192,   192,   192,   192,   192,   192,   192,    41,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
    92,    92,    92,    92,    92,    92,    92,   112,    36,    36,
    36,    36,    36,    36,    36,    36,    36,    36,    36,    36,
    36,    36,    36,    70,    60,   146,   148,    59,    57,    52,
    43,   176,   177,    37,    34,    33,    28,   187,    27,    21,
    19,   194,   195,   196,   197,   199,   201,    18,   207,   208,
    16,   210,   211,    14,   215,   216,     2,   219,   220,   222,
   228,   229,   232 ]

racc_action_pointer = [
    -5,   160,   223,   nil,     0,    -2,   nil,   nil,   178,   nil,
    92,   nil,   nil,     4,   225,   nil,   280,   nil,   246,   262,
   nil,   203,   nil,   nil,   nil,   nil,     2,   210,   208,   nil,
   nil,    78,   nil,   257,   236,   nil,   206,   203,    24,   nil,
   nil,   155,   123,   194,   nil,   nil,   nil,   nil,   109,   nil,
   nil,   nil,   211,   nil,   nil,   nil,   nil,   230,   nil,   190,
   188,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   189,   nil,   nil,   nil,   nil,   nil,   nil,   140,   178,    98,
   nil,   126,   nil,    76,   nil,   nil,    90,   nil,   nil,   nil,
   nil,    56,   218,   nil,   nil,    67,   nil,   -33,    30,   nil,
    54,   nil,    16,    12,    54,   nil,    42,    86,   nil,   -53,
   nil,   nil,   173,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    65,   nil,   nil,   nil,    43,   nil,   nil,
   126,   nil,   nil,   139,    -1,   nil,    -7,    -8,   nil,    66,
   nil,   nil,   nil,   nil,   nil,   nil,   247,   nil,   190,   nil,
    18,   nil,   nil,   nil,   nil,   nil,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   103,   198,   193,   nil,   nil,
   124,   nil,   nil,   171,    18,   nil,    31,   238,    29,   nil,
    -5,   nil,   200,   nil,   208,   214,   209,   216,   nil,   211,
   nil,   208,   nil,   nil,   nil,   nil,    19,   210,   211,    -6,
   221,   223,   nil,   nil,   119,   221,   222,   nil,     5,   224,
   228,   nil,   281,   nil,   nil,   nil,   nil,   nil,   226,   227,
   nil,   nil,   224,   nil,   nil ]

racc_action_default = [
    -1,  -160,  -160,   -26,   -25,  -160,    -2,    -4,  -160,    -5,
  -160,    -6,    -7,  -160,   -12,  -154,  -160,    -3,  -160,  -160,
  -135,  -160,  -133,  -136,  -134,   -28,   -33,   -12,   -12,   -11,
   -10,  -160,   235,  -160,   -44,   -48,  -160,  -160,  -160,   -34,
   -36,   -25,  -100,   -31,    -9,    -8,  -112,  -114,  -160,  -113,
   -14,  -115,   -16,   -17,   -18,  -110,  -111,   -44,   -45,  -160,
   -46,   -71,   -60,   -72,   -61,   -73,   -62,   -63,   -64,   -65,
   -86,   -66,   -67,   -68,   -69,   -74,   -70,  -131,  -160,  -160,
   -27,  -160,  -109,  -106,  -104,  -103,  -160,  -105,  -107,  -108,
  -101,  -160,  -160,   -30,   -13,  -160,  -116,  -160,  -160,   -49,
  -160,   -47,  -160,   -93,   -91,   -87,  -160,  -160,  -132,  -160,
   -29,   -35,   -25,   -99,   -37,   -38,   -39,   -40,   -41,   -43,
   -42,   -32,   -15,   -25,   -50,   -51,   -20,   -25,  -137,   -94,
  -160,   -92,  -130,  -160,  -160,  -102,  -160,   -25,  -156,   -25,
   -96,   -95,   -98,   -97,  -118,  -117,  -160,  -122,  -160,   -90,
  -160,  -146,  -144,  -147,  -148,  -149,  -160,  -139,  -150,  -145,
  -142,  -143,  -141,  -129,   -58,   -56,  -160,  -128,   -55,  -155,
  -157,   -21,   -22,   -23,   -24,  -160,  -160,  -160,  -119,  -121,
  -160,  -152,  -138,  -160,   -25,  -159,  -160,   -75,  -160,   -19,
  -160,  -151,  -160,  -140,  -160,  -160,   -86,   -55,   -76,   -86,
   -57,  -160,  -123,  -125,  -153,  -158,   -25,   -93,   -93,   -25,
  -124,  -160,   -78,   -80,  -160,  -160,  -160,  -127,  -160,  -160,
   -79,   -83,  -160,   -84,   -52,   -53,  -126,   -54,   -25,   -86,
   -85,   -81,   -88,   -82,   -89 ]

racc_goto_table = [
     5,    70,   103,    34,     5,   128,   121,    25,   141,    81,
    90,    52,   157,    50,    53,   188,   203,    57,    60,    30,
   213,   138,     6,     2,    91,    43,    17,     2,    39,    21,
    40,   101,    44,    45,    99,   170,    38,   196,   174,   173,
   172,    97,   231,   199,   226,   195,   211,   212,   171,   220,
   222,   229,   233,   234,   223,   130,   139,    93,   102,   178,
   202,   193,    48,   210,   181,   194,   166,    37,    77,   106,
   108,   156,    27,   180,   137,    52,   110,   122,    53,     4,
   135,   nil,   nil,   nil,   125,   nil,   nil,   nil,   nil,   nil,
   217,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   204,   nil,   nil,   215,
   216,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   136,   nil,   nil,   nil,   nil,   207,   nil,
   177,   208,   nil,   nil,   nil,   nil,   nil,   136,   nil,   175,
   186,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   232,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   221,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   214,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   214 ]

racc_goto_check = [
    13,    35,    37,    14,    13,    38,    28,    23,    52,    30,
    30,    11,    69,    10,    12,    39,    61,    14,    15,     7,
    44,    72,     2,    55,    54,    26,     2,    55,    29,    25,
    31,    33,     7,     7,    34,    72,    24,    36,    21,    20,
    19,    15,    44,    40,    61,    41,    42,    43,    18,    45,
    46,    47,    48,    50,    39,    51,    17,    27,    16,    58,
    60,    69,     9,    62,    28,    52,    63,    64,    65,    66,
    67,    68,     8,    70,    71,    11,    23,    10,    12,     1,
    30,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,
    52,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,   nil,    38,
    38,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,    37,   nil,
    14,    37,   nil,   nil,   nil,   nil,   nil,    13,   nil,    13,
    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    37,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    13 ]

racc_goto_pointer = [
   nil,    79,    22,   nil,   nil,   nil,   nil,     5,    59,    31,
   -18,   -20,   -17,     0,   -16,   -16,    -2,   -70,   -91,   -99,
  -100,  -101,   nil,    -3,    11,    21,    -1,    14,   -86,     2,
   -32,     4,   nil,   -29,   -25,   -35,  -149,   -68,   -98,  -160,
  -145,  -141,  -160,  -159,  -186,  -164,  -164,  -171,  -180,   nil,
  -179,   -49,  -119,   nil,   -18,    23,   nil,   nil,   -87,   nil,
  -130,  -174,  -140,   -70,    46,    31,    -8,    -7,   -63,  -122,
   -77,   -49,  -102 ]

racc_goto_default = [
   nil,   nil,   nil,     7,     9,    11,    12,   nil,   nil,   nil,
   nil,    83,    85,    86,   187,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     3,   nil,   nil,    26,   nil,   nil,   nil,   nil,
   140,   143,    58,   nil,   144,   nil,   167,   nil,   nil,   nil,
   163,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   105,
   129,   nil,   nil,   142,   nil,    82,   145,   146,   nil,   148,
   nil,   nil,   nil,   201,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "*" => 2,
 "/" => 3,
 "+" => 4,
 "-" => 5,
 :PRAGMA => 6,
 :INCLUDE => 7,
 :IDENTIFIER => 8,
 :CLASS => 9,
 :ASSOCIATION => 10,
 :INDICATION => 11,
 :AMENDED => 12,
 :ENABLEOVERRIDE => 13,
 :DISABLEOVERRIDE => 14,
 :RESTRICTED => 15,
 :TOSUBCLASS => 16,
 :TOINSTANCE => 17,
 :TRANSLATABLE => 18,
 :QUALIFIER => 19,
 :SCOPE => 20,
 :SCHEMA => 21,
 :PROPERTY => 22,
 :REFERENCE => 23,
 :METHOD => 24,
 :PARAMETER => 25,
 :FLAVOR => 26,
 :INSTANCE => 27,
 :AS => 28,
 :REF => 29,
 :ANY => 30,
 :OF => 31,
 :DT_VOID => 32,
 :DT_UINT8 => 33,
 :DT_SINT8 => 34,
 :DT_UINT16 => 35,
 :DT_SINT16 => 36,
 :DT_UINT32 => 37,
 :DT_SINT32 => 38,
 :DT_UINT64 => 39,
 :DT_SINT64 => 40,
 :DT_REAL32 => 41,
 :DT_REAL64 => 42,
 :DT_CHAR16 => 43,
 :DT_STR => 44,
 :DT_BOOLEAN => 45,
 :DT_DATETIME => 46,
 :positiveDecimalValue => 47,
 :stringValue => 48,
 :realValue => 49,
 :charValue => 50,
 :booleanValue => 51,
 :nullValue => 52,
 :binaryValue => 53,
 :octalValue => 54,
 :decimalValue => 55,
 :hexValue => 56,
 "#" => 57,
 "(" => 58,
 ")" => 59,
 "," => 60,
 "{" => 61,
 "}" => 62,
 ";" => 63,
 "[" => 64,
 "]" => 65,
 ":" => 66,
 "$" => 67,
 "=" => 68,
 "." => 69 }

racc_use_result_var = true

racc_nt_base = 70

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"*"',
'"/"',
'"+"',
'"-"',
'PRAGMA',
'INCLUDE',
'IDENTIFIER',
'CLASS',
'ASSOCIATION',
'INDICATION',
'AMENDED',
'ENABLEOVERRIDE',
'DISABLEOVERRIDE',
'RESTRICTED',
'TOSUBCLASS',
'TOINSTANCE',
'TRANSLATABLE',
'QUALIFIER',
'SCOPE',
'SCHEMA',
'PROPERTY',
'REFERENCE',
'METHOD',
'PARAMETER',
'FLAVOR',
'INSTANCE',
'AS',
'REF',
'ANY',
'OF',
'DT_VOID',
'DT_UINT8',
'DT_SINT8',
'DT_UINT16',
'DT_SINT16',
'DT_UINT32',
'DT_SINT32',
'DT_UINT64',
'DT_SINT64',
'DT_REAL32',
'DT_REAL64',
'DT_CHAR16',
'DT_STR',
'DT_BOOLEAN',
'DT_DATETIME',
'positiveDecimalValue',
'stringValue',
'realValue',
'charValue',
'booleanValue',
'nullValue',
'binaryValue',
'octalValue',
'decimalValue',
'hexValue',
'"#"',
'"("',
'")"',
'","',
'"{"',
'"}"',
'";"',
'"["',
'"]"',
'":"',
'"$"',
'"="',
'"."',
'$start',
'mofSpecification',
'mofProduction',
'compilerDirective',
'classDeclaration',
'qualifierDeclaration',
'instanceDeclaration',
'pragmaParameters_opt',
'pragmaName',
'pragmaParameterValues',
'pragmaParameterValue',
'string',
'integerValue',
'qualifierList_opt',
'className',
'alias_opt',
'superClass_opt',
'classFeatures',
'classFeature',
'propertyDeclaration',
'methodDeclaration',
'referenceDeclaration',
'qualifierList',
'qualifier',
'qualifiers',
'qualifierName',
'qualifierParameter_opt',
'flavor_opt',
'flavor',
'qualifierParameter',
'constantValue',
'arrayInitializer',
'alias',
'superClass',
'aliasIdentifier',
'dataType',
'propertyName',
'array_opt',
'defaultValue_opt',
'objectRef',
'referenceName',
'methodName',
'parameterList_opt',
'parameterList',
'parameter',
'parameters',
'typespec',
'parameterName',
'parameterValue_opt',
'array',
'defaultValue',
'positiveDecimalValue_opt',
'initializer',
'referenceInitializer',
'constantValues',
'instance',
'objectHandle',
'namespace_opt',
'modelPath',
'namespaceHandle',
'keyValuePairList',
'keyValuePair',
'keyValuePairs',
'keyname',
'qualifierType',
'scope',
'defaultFlavor_opt',
'defaultFlavor',
'metaElements',
'metaElement',
'flavors',
'valueInitializers',
'valueInitializer']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 37
  def _reduce_1( val, _values, result )
 result = Hash.new
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 39
  def _reduce_2( val, _values, result )
 result = { @name => @result }
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 43
  def _reduce_3( val, _values, result )
 result = val[0]
	    result[@name] = @result
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 51
  def _reduce_5( val, _values, result )
 #puts "Class '#{val[0].name}'"
	    @result.classes << val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 55
  def _reduce_6( val, _values, result )
 @result.qualifiers << val[0]
	    @qualifiers[val[0].name.downcase] = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 57
  def _reduce_7( val, _values, result )
 @result.instances << val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 69
  def _reduce_8( val, _values, result )
 raise MOF::Helper::Error.new(@name,@lineno,@line,"Missing filename after '#pragma include'") unless val[3]
	    open val[3], :pragma
   result
  end
.,.,

 # reduce 9 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 75
  def _reduce_10( val, _values, result )
 raise StyleError.new(@name,@lineno,@line,"Use '#pragma include' instead of '#include'") unless @style == :wmi
	    raise MOF::Helper::Error.new(@name,@lineno,@line,"Missing filename after '#include'") unless val[2]
	    open val[2], :pragma
   result
  end
.,.,

 # reduce 11 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 84
  def _reduce_12( val, _values, result )
 raise StyleError.new(@name,@lineno,@line,"#pragma parameter missing") unless @style == :wmi
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 86
  def _reduce_13( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 97
  def _reduce_17( val, _values, result )
 raise StyleError.new(@name,@lineno,@line,"#pragma parameter missing") unless @style == :wmi
   result
  end
.,.,

 # reduce 18 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 112
  def _reduce_19( val, _values, result )
 qualifiers = val[0]
	    features = val[6]
	    # FIXME: features must not include references
	    result = CIM::Class.new(val[2],qualifiers,val[3],val[4],features)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 117
  def _reduce_20( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 119
  def _reduce_21( val, _values, result )
 result = val[0] << val[1]
   result
  end
.,.,

 # reduce 22 omitted

 # reduce 23 omitted

 # reduce 24 omitted

 # reduce 25 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 132
  def _reduce_26( val, _values, result )
 result = CIM::QualifierSet.new val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 138
  def _reduce_27( val, _values, result )
 result = val[2]
	    result.unshift val[1] if val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 143
  def _reduce_28( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 147
  def _reduce_29( val, _values, result )
 result = val[0]
	    result << val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 169
  def _reduce_30( val, _values, result )
 # Get qualifier decl
	    qualifier = case val[0]
	      when CIM::Qualifier then            val[0].definition
	      when CIM::QualifierDeclaration then val[0]
	      when String then                    @qualifiers[val[0].downcase]
	    else
	      nil
	    end
	    raise MOF::Helper::Error.new(@name,@lineno,@line,"'#{val[0]}' is not a valid qualifier") unless qualifier
	    value = val[1]
	    raise MOF::Helper::Error.new(@name,@lineno,@line,"#{value.inspect} does not match qualifier type '#{qualifier.type}'") unless qualifier.type.matches?(value)||@style == :wmi
	    # Don't propagate a boolean 'false'
	    if qualifier.type == :boolean && value == false
	      result = nil
	    else
	      result = CIM::Qualifier.new(qualifier,value,val[2])
	    end
   result
  end
.,.,

 # reduce 31 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 175
  def _reduce_32( val, _values, result )
 result = CIM::QualifierFlavors.new val[1]
   result
  end
.,.,

 # reduce 33 omitted

 # reduce 34 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 185
  def _reduce_35( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 36 omitted

 # reduce 37 omitted

 # reduce 38 omitted

 # reduce 39 omitted

 # reduce 40 omitted

 # reduce 41 omitted

 # reduce 42 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 196
  def _reduce_43( val, _values, result )
 case val[0].to_sym
	      when :amended, :toinstance
	        raise StyleError.new(@name,@lineno,@line,"'#{val[0]}' is not a valid flavor") unless @style == :wmi
	    end
   result
  end
.,.,

 # reduce 44 omitted

 # reduce 45 omitted

 # reduce 46 omitted

 # reduce 47 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 211
  def _reduce_48( val, _values, result )
 raise ParseError.new("Class name must be prefixed by '<schema>_'") unless @style == :wmi
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 216
  def _reduce_49( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 221
  def _reduce_50( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 226
  def _reduce_51( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 238
  def _reduce_52( val, _values, result )
 if val[3]
	      type = CIM::Array.new val[3],val[1]
	    else
	      type = val[1]
	    end
	    result = CIM::Property.new(type,val[2],val[0],val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 246
  def _reduce_53( val, _values, result )
 if val[4]
	      raise StyleError.new(@name,@lineno,@line,"Array not allowed in reference declaration") unless @style == :wmi
	    end
	    result = CIM::Reference.new(val[1],val[2],val[0],val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 251
  def _reduce_54( val, _values, result )
 result = CIM::Method.new(val[1],val[2],val[0],val[4])
   result
  end
.,.,

 # reduce 55 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 259
  def _reduce_56( val, _values, result )
 # tmplprov.mof has 'string Property;'
	    raise StyleError.new(@name,@lineno,@line,"Invalid keyword '#{val[0]}' used for property name") unless @style == :wmi
   result
  end
.,.,

 # reduce 57 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 265
  def _reduce_58( val, _values, result )
 result = "Indication"
   result
  end
.,.,

 # reduce 59 omitted

 # reduce 60 omitted

 # reduce 61 omitted

 # reduce 62 omitted

 # reduce 63 omitted

 # reduce 64 omitted

 # reduce 65 omitted

 # reduce 66 omitted

 # reduce 67 omitted

 # reduce 68 omitted

 # reduce 69 omitted

 # reduce 70 omitted

 # reduce 71 omitted

 # reduce 72 omitted

 # reduce 73 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 288
  def _reduce_74( val, _values, result )
 raise StyleError.new(@name,@lineno,@line,"'void' is not a valid datatype") unless @style == :wmi
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 296
  def _reduce_75( val, _values, result )
 # WMI uses class names as data types (without REF ?!)
	    raise StyleError.new(@name,@lineno,@line,"Expected 'ref' keyword after classname '#{val[0]}'") unless @style == :wmi
	    result = CIM::ReferenceType.new val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 299
  def _reduce_76( val, _values, result )
 result = CIM::ReferenceType.new val[0]
   result
  end
.,.,

 # reduce 77 omitted

 # reduce 78 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 309
  def _reduce_79( val, _values, result )
 result = val[1].unshift val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 314
  def _reduce_80( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 316
  def _reduce_81( val, _values, result )
 result = val[0] << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 327
  def _reduce_82( val, _values, result )
 if val[3]
	      type = CIM::Array.new val[3], val[1]
	    else
	      type = val[1]
	    end
	    result = CIM::Property.new(type,val[2],val[0])
   result
  end
.,.,

 # reduce 83 omitted

 # reduce 84 omitted

 # reduce 85 omitted

 # reduce 86 omitted

 # reduce 87 omitted

 # reduce 88 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 347
  def _reduce_89( val, _values, result )
 raise "Default parameter value not allowed in syntax style '{@style}'" unless @style == :wmi
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 352
  def _reduce_90( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 357
  def _reduce_91( val, _values, result )
 result = -1
   result
  end
.,.,

 # reduce 92 omitted

 # reduce 93 omitted

 # reduce 94 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 368
  def _reduce_95( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 96 omitted

 # reduce 97 omitted

 # reduce 98 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 379
  def _reduce_99( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 100 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 385
  def _reduce_101( val, _values, result )
 result = [ val[0] ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 387
  def _reduce_102( val, _values, result )
 result = val[0] << val[2]
   result
  end
.,.,

 # reduce 103 omitted

 # reduce 104 omitted

 # reduce 105 omitted

 # reduce 106 omitted

 # reduce 107 omitted

 # reduce 108 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 398
  def _reduce_109( val, _values, result )
 raise "Instance as property value not allowed in syntax style '{@style}'" unless @style == :wmi
   result
  end
.,.,

 # reduce 110 omitted

 # reduce 111 omitted

 # reduce 112 omitted

 # reduce 113 omitted

 # reduce 114 omitted

 # reduce 115 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 412
  def _reduce_116( val, _values, result )
 result = val[0] + val[1]
   result
  end
.,.,

 # reduce 117 omitted

 # reduce 118 omitted

 # reduce 119 omitted

 # reduce 120 omitted

 # reduce 121 omitted

 # reduce 122 omitted

 # reduce 123 omitted

 # reduce 124 omitted

 # reduce 125 omitted

 # reduce 126 omitted

 # reduce 127 omitted

 # reduce 128 omitted

 # reduce 129 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 467
  def _reduce_130( val, _values, result )
 result = CIM::QualifierDeclaration.new( val[1], val[2][0], val[2][1], val[3], val[4])
   result
  end
.,.,

 # reduce 131 omitted

 # reduce 132 omitted

 # reduce 133 omitted

 # reduce 134 omitted

 # reduce 135 omitted

 # reduce 136 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 487
  def _reduce_137( val, _values, result )
 type = val[2].nil? ? val[1] : CIM::Array.new(val[2],val[1])
	    result = [ type, val[3] ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 492
  def _reduce_138( val, _values, result )
 result = CIM::QualifierScopes.new(val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 497
  def _reduce_139( val, _values, result )
 result = [ val[0] ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 499
  def _reduce_140( val, _values, result )
 result = val[0] << val[2]
   result
  end
.,.,

 # reduce 141 omitted

 # reduce 142 omitted

 # reduce 143 omitted

 # reduce 144 omitted

 # reduce 145 omitted

 # reduce 146 omitted

 # reduce 147 omitted

 # reduce 148 omitted

 # reduce 149 omitted

 # reduce 150 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 517
  def _reduce_151( val, _values, result )
 result = CIM::QualifierFlavors.new val[3]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 522
  def _reduce_152( val, _values, result )
 result = [ val[0] ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/mof/parser.y', 524
  def _reduce_153( val, _values, result )
 result = val[0] << val[2]
   result
  end
.,.,

 # reduce 154 omitted

 # reduce 155 omitted

 # reduce 156 omitted

 # reduce 157 omitted

 # reduce 158 omitted

module_eval <<'.,.,', 'lib/mof/parser.y', 548
  def _reduce_159( val, _values, result )
 raise "Instance property '#{val[1]} must have a value" unless @style == :wmi
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module MOF
